- we build a simple NN
- Train it on a real world dataset
- will mimic the Pytorch workflow
- will have a lot of manual elements
- End result is not important

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Kajal\Downloads\breast-cancer.csv")

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df.drop(columns=['id'],inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
print(StandardScaler)

<class 'sklearn.preprocessing._data.StandardScaler'>

In [10]:
X_train

array([[-0.11473896, -0.81156166, -0.08499165, ...,  0.34825501,
        -0.49269746,  1.07769421],
       [ 1.08878871,  0.29400192,  1.07625706, ...,  0.51185488,
         0.54161626, -0.43371847],
       [ 0.3083539 ,  0.72278445,  0.26749321, ...,  0.10594199,
         0.4228733 ,  0.77936677],
       ...,
       [-0.57785413, -0.33642427, -0.60977477, ..., -0.87843534,
        -1.05828895, -0.57440698],
       [-0.36916643, -0.68640352, -0.4129811 , ..., -0.5152745 ,
         0.18694978, -0.815668  ],
       [-0.32914413, -0.16259352, -0.30669591, ...,  0.15533063,
         0.32600404, -0.04272872]])

In [11]:
y_train

73     M
492    M
184    M
150    B
158    B
      ..
327    B
407    B
96     B
195    B
356    B
Name: diagnosis, Length: 455, dtype: object

#### Label Encoding

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [14]:
y_test

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1])

### Numpy arrays to Pytorch tensors

In [15]:
import torch
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor.shape

torch.Size([455, 30])

In [17]:
y_train_tensor.shape

torch.Size([455])

In [18]:
X_test_tensor.shape

torch.Size([114, 30])

In [19]:
y_test_tensor.shape

torch.Size([114])

In [20]:
y_test_tensor

tensor([1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1],
       dtype=torch.int32)

### Defining the model

In [21]:
class MySimpleNN():
    def __init__(self,X):
       self.weights =   torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
       self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True) 

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        #clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        # calculate loss
        loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss         
        
    # def binary_cross_entropy_loss(prediction,target):
    #  epsilon = 1e-8 #to prevent log(0)
    #  return - (target * torch.log(prediction) + (1-target)*torch.log(1-prediction))

### Important Parameters

In [28]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [23]:
#create model
model = MySimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):
   #forward pass
   y_pred = model.forward(X_train_tensor)
  
   #loss calculation
   loss =model.loss_function(y_pred,y_train_tensor)
      
   #backward pass
   loss.backward()
   #parameters update
   with torch.no_grad(): 
    model.weights -= learning_rate*model.weights.grad
    model.bias -= learning_rate*model.bias.grad
   # zero gradients 
   model.weights.grad.zero_()
   model.bias.grad.zero_() 
   #print loss in each epoch
   print(f'Epoch: {epoch},Loss:{loss.item()}')

Epoch: 0,Loss:4.003489482683657
Epoch: 1,Loss:3.8793864691988196
Epoch: 2,Loss:3.7473926439512284
Epoch: 3,Loss:3.6107956189281607
Epoch: 4,Loss:3.462318875447382
Epoch: 5,Loss:3.308996934203007
Epoch: 6,Loss:3.1489443258875403
Epoch: 7,Loss:2.9832719722149355
Epoch: 8,Loss:2.814413023627769
Epoch: 9,Loss:2.6417513870322415
Epoch: 10,Loss:2.464851882542903
Epoch: 11,Loss:2.2818865785848503
Epoch: 12,Loss:2.098758730279697
Epoch: 13,Loss:1.9186583264959614
Epoch: 14,Loss:1.738715289419719
Epoch: 15,Loss:1.5646204010313447
Epoch: 16,Loss:1.4020968705542662
Epoch: 17,Loss:1.2539595076293697
Epoch: 18,Loss:1.1232012028222724
Epoch: 19,Loss:1.0126043473953235
Epoch: 20,Loss:0.924101100555781
Epoch: 21,Loss:0.8578938408358239
Epoch: 22,Loss:0.8118172693508836
Epoch: 23,Loss:0.7816639279354253
Epoch: 24,Loss:0.7625207634125274

In [24]:
model.bias

tensor([-0.1259], dtype=torch.float64, requires_grad=True)

### Evalution

In [25]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6777470111846924

In [26]:
import os
print(os.getcwd())

C:\Users\Kajal\PYTORCH

In [39]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):

        out = self.linear(features)
        out = self.sigmoid(out)
        return self.linear(x)
        
   

     
    def loss_function(self,y_pred,y):
        #clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        # calculate loss
        loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

In [40]:
learning_rate = 0.1
epochs = 25

In [41]:
loss_function = nn.BCELoss()

In [44]:
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

In [43]:
#create model
model = MySimpleNN(X_train_tensor.shape[1])

#define loop
for epoch in range(epochs):
   #forward pass
   y_pred = model(X_train_tensor)
  
   #loss calculation
   loss =model.loss_function(y_pred,y_train_tensor)
      
   #backward pass
   loss.backward()
   #parameters update
   with torch.no_grad(): 
     model.linear.weight -= learning_rate*model.linear.weight.grad
     model.linear.bias -= learning_rate*model.linear.bias.grad
   # zero gradients 
   model.linear.weight.grad.zero_()
   model.linear.bias.grad.zero_() 
   #print loss in each epoch
   print(f'Epoch: {epoch+1},Loss:{loss.item()}')

RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float

In [ ]:
model.linear.weight